# -*- coding: utf-8 -*-
"""Projeto Básico

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_2kWYvqvOWSBEaWASV8vRaEfhyZidqdl

Istalando o SDK Do Google
"""

!pip  install -q -U google-generativeai

"""Criação do Acesso API KEY"""

import google.generativeai as genai


GOOGLE_API_KEY = "AIzaSyA_OJ9wk9gUTw4qUlVk0ieV_rvu0eJyw_A"
genai.configure(api_key=GOOGLE_API_KEY)

"""Lista de Modelos"""

for m in genai.list_models():
  if 'generateContent'in m.supported_generation_methods:
    print(m.name)

"""Recolarizando as Varíaveis e Propabilidade"""

generation_config={

    "candidate_count":1,
    "temperature":0.5,
    "top_p":1

}

"""Recolarizando os Conteúdos Sensíves e impróprios"""

safety_settings= {

    "HARASSMENT": "BLOCK_NONE",
    "HATE":"BLOCK_NONE" ,
    "SEXUAL":"BLOCK_NONE" ,
    "DANGEROUS":"BLOCK_NONE"

}

"""Inicializando o Modelo"""

model =genai.GenerativeModel(model_name="gemini-1.0-pro",

                             generation_config=generation_config,
                             safety_settings=safety_settings
                             )

"""Texte Do Código"""

response = model.generate_content("Vamos aprender conteúdo sobre AI . Me dê sugestões envolvendo redes de computadores.")
print(response.text)

"""Iniciando ChatBot"""

chat = model.start_chat(history=[])

prompt = input("Esperando prompt: ")

while prompt != "fim":
  response = chat.send_message(prompt)
  print("Resposta: ", response.text,"\n")
  prompt = input ("Esperando prompt: ")